# Generated by Django 5.1.7 on 2025-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_readingexercise_is_public_readingexercise_is_ranked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("open", "Otwarte"), ("choice", "Zamknięte (4 odpowiedzi)")],
                default="open",
                max_length=10,
            ),
        ),
    ]
