# Generated by Django 5.1.7 on 2025-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_question_option_1_question_option_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mode",
            field=models.CharField(
                choices=[("rsvp", "RSVP"), ("highlight", "Highlight")],
                default="rsvp",
                max_length=20,
            ),
        ),
    ]
