# Generated by Django 5.1.7 on 2025-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customuser_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="highlightHeight",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="customuser",
            name="highlightWidth",
            field=models.IntegerField(default=600),
        ),
    ]
