# Generated by Django 5.1.7 on 2025-06-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_customuser_highlightheight_customuser_highlightwidth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="highlightHeight",
            new_name="highlight_height",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="highlightWidth",
            new_name="highlight_width",
        ),
    ]
