# Generated by Django 5.1.7 on 2025-10-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_highlightheight_customuser_highlight_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chunk_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mode',
            field=models.CharField(choices=[('rsvp', 'RSVP'), ('highlight', 'Highlight'), ('chunking', 'Chunking')], default='rsvp', max_length=20),
        ),
    ]
