# Generated by Django 5.1.7 on 2025-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_chunk_size_alter_customuser_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_wpm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ranking_exercises_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_ranking_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='counted_for_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='ranking_points',
            field=models.IntegerField(default=0),
        ),
    ]
