# Generated by Django 5.1.7 on 2025-10-27 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingexercise',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='readingexercise',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
