# Generated by Django 5.1.7 on 2025-10-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_daily_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.readingexercise'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
