# Generated by Django 5.1.7 on 2025-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprogress_completed_daily_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingexercise',
            name='word_count',
            field=models.IntegerField(default=0, editable=False, help_text='Automatycznie liczona liczba słów'),
        ),
    ]
