# Generated by Django 5.1.7 on 2025-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_readingexercise_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Aktualna seria codziennych treningów'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_streak_date',
            field=models.DateField(blank=True, help_text='Data ostatniego zaliczonego treningu w serii', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_streak',
            field=models.IntegerField(default=0, help_text='Najdłuższa osiągnięta seria'),
        ),
    ]
