# Generated by Django 5.1.7 on 2025-11-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_current_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, help_text='Opis kolekcji')),
                ('icon_name', models.CharField(default='📚', help_text='Emoji lub nazwa ikony', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Czy kolekcja jest widoczna dla wszystkich?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(blank=True, help_text='Ćwiczenia zawarte w tej kolekcji', related_name='collections', to='api.readingexercise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
