# Generated by Django 5.1.7 on 2025-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='cheating_reason',
            field=models.CharField(blank=True, help_text='Powód oznaczenia jako oszustwo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='is_cheating_attempt',
            field=models.BooleanField(default=False, help_text='Czy wykryto próbę oszustwa podczas tej sesji'),
        ),
    ]
