# Generated by Django 5.1.7 on 2025-11-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprogress_cheating_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='cheating_reason',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='is_cheating_attempt',
        ),
    ]
