# Generated by Django 5.1.7 on 2025-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_userprogress_cheating_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon_name',
            field=models.CharField(default='🏆', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='slug',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='average_accuracy',
            field=models.FloatField(default=0, help_text='Średnia accuracy z ZALICZONYCH prób'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='average_wpm',
            field=models.FloatField(default=0, help_text='Średnie WPM z ZALICZONYCH prób'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_streak_date',
            field=models.DateField(blank=True, help_text='Data ostatniego treningu', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ranking_exercises_completed',
            field=models.IntegerField(default=0, help_text='Liczba ZALICZONYCH prób rankingowych'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_ranking_points',
            field=models.IntegerField(default=0, help_text='Suma punktów z ZALICZONYCH prób (accuracy >= 60%)'),
        ),
        migrations.AlterField(
            model_name='exercisecollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercisecollection',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='collections', to='api.readingexercise'),
        ),
        migrations.AlterField(
            model_name='exercisecollection',
            name='icon_name',
            field=models.CharField(default='📚', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercisecollection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readingexercise',
            name='word_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='accuracy',
            field=models.FloatField(help_text='Trafność w quizie (0-100)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Która to próba użytkownika dla tego ćwiczenia'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='counted_for_ranking',
            field=models.BooleanField(default=False, help_text='Czy ten wynik liczy się do rankingu'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='ranking_points',
            field=models.IntegerField(default=0, help_text='Punkty rankingowe (0 jeśli accuracy < 60)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='wpm',
            field=models.IntegerField(help_text='Słowa na minutę (obliczone z word_count / minuty)'),
        ),
    ]
