# Generated by Django 5.1.7 on 2025-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customuser_avatar_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_wpm_limit',
            field=models.IntegerField(default=350, help_text='Maksymalny odblokowany WPM przez użytkownika'),
        ),
    ]
