# Generated by Django 5.1.7 on 2025-11-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customuser_max_wpm_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_calibration',
            field=models.BooleanField(default=False, help_text='Czy użytkownik przeszedł pierwszą kalibrację ustawień'),
        ),
    ]
