# Generated by Django 5.1.7 on 2025-11-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
