# Generated by Django 5.1.7 on 2025-11-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data wyzwania (YYYY-MM-DD)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(help_text='Ćwiczenie rankingowe na ten dzień', limit_choices_to={'is_public': True, 'is_ranked': True}, on_delete=django.db.models.deletion.CASCADE, to='api.readingexercise')),
            ],
            options={
                'verbose_name': 'Wyzwanie Dnia',
                'verbose_name_plural': 'Wyzwania Dnia',
                'ordering': ['-date'],
            },
        ),
    ]
