# Generated by Django 5.1.7 on 2025-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_dailychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingexercise',
            name='is_daily_candidate',
            field=models.BooleanField(default=False, help_text='Czy to ćwiczenie jest w ukrytej puli do losowania Daily Challenge?'),
        ),
    ]
