# Generated by Django 5.1.7 on 2025-12-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_readingexercise_is_daily_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mode',
            field=models.CharField(choices=[('rsvp', 'RSVP'), ('rsvp-orp', 'RSVP-ORP'), ('highlight', 'Highlight'), ('chunking', 'Chunking')], default='rsvp', max_length=20),
        ),
    ]
