# Generated by Django 5.1.7 on 2026-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_customuser_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mode',
            field=models.CharField(choices=[('rsvp', 'RSVP'), ('highlight', 'Highlight'), ('chunking', 'Chunking')], default='rsvp', max_length=20),
        ),
    ]
