# Generated by Django 5.1.7 on 2026-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customuser_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=10),
        ),
    ]
