# Generated by Django 5.1.7 on 2026-01-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_achievement_icon_name_achievement_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon_name',
            field=models.CharField(default='🏆', max_length=50),
        ),
    ]
